resilience4j.circuitbreaker:
  instances:
    dummyService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      sliding-window-type: COUNT_BASED
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50


